#ifndef GLOBAL_H
#define GLOBAL_H

//NOTE: THIS VALUE MAY HAVE TO BE CHANGED DEPENING ON THE SCALE OF THE SCENE. INCORRECT VALUES CAN CAUSE INCORRECT INTERSECTION CALCULATIONS AND LEAD TO GRAHICAL ARTIFACTING
#define EPSILON 1e-4f
#define PI 3.1415927f

typedef float Vec3[3];
typedef struct Line Line;

typedef struct Line {
	Vec3 vector;
	Vec3 position;
} Line;

#endif
